import type { Metadata } from "next";
import Link from "next/link";
import { Masthead, PolicyBody } from "@/components/site/chrome";

export const metadata: Metadata = {
  title: "Security",
  description: "How Veridion authenticates users, isolates workspaces, handles uploads and records activity — and how to report a vulnerability.",
};

export default function SecurityPage() {
  return (
    <>
      <Masthead title="Security" lead="The controls that exist in Veridion today. Where something depends on how a deployment is hosted, we say so." />
      <PolicyBody>
        <h2>Accounts and sign-in</h2>
        <ul>
          <li>Passwords are never stored. Veridion stores a salted scrypt hash (N = 2¹⁵, r = 8, p = 1) and compares hashes in constant time.</li>
          <li>Passwords must be at least ten characters. Failed sign-ins return the same message whether or not the account exists.</li>
          <li>
            Sign-in is rate limited per network address and per account; registration and website enquiries per network
            address.
          </li>
        </ul>

        <h2>Sessions</h2>
        <ul>
          <li>After sign-in, the browser holds a signed session token in an <code>HttpOnly</code>, <code>SameSite=Lax</code> cookie that scripts cannot read. Deployments served over HTTPS also mark it <code>Secure</code>; this is a deployment setting, and the server warns at startup in production when it is off.</li>
          <li>Sessions expire after seven days.</li>
          <li>Requests that change data using the cookie must also carry a header set only by the Veridion web client, which protects against cross-site request forgery.</li>
          <li>Programmatic clients send the session token as a bearer credential instead of a cookie.</li>
        </ul>

        <h2>Workspace isolation and roles</h2>
        <p>
          Every company, document, passage, assessment, finding, review and action belongs to exactly one organization, and every
          query is filtered by the caller&apos;s organization. A request for another organization&apos;s record is answered as if
          the record did not exist. This behaviour is covered by the automated test suite.
        </p>
        <p>
          Within an organization, members have one of five roles. Owners and admins manage members and settings; analysts upload
          documents and run assessments; reviewers record decisions on findings and actions; viewers can read but not change
          anything.
        </p>

        <h2>Documents</h2>
        <ul>
          <li>Only PDF files are accepted, up to 50 MB, and the file signature is checked on upload.</li>
          <li>Storage locations are generated by the server; file names supplied by users are never used as paths.</li>
          <li>Documents are processed by background workers, not in the web request. Encrypted or unreadable files are rejected with a clear error.</li>
          <li>A document that findings cite cannot be deleted, only replaced by a new version, so past assessments remain auditable.</li>
        </ul>

        <h2>Activity records</h2>
        <p>
          Sign-ins, failed sign-ins, uploads, assessment runs, reviews, overrides, exports, applicability decisions, and member and
          plan changes are written to an append-only audit log that owners and admins can read in the workspace settings.
        </p>

        <h2>Web protections</h2>
        <p>
          The website and application send headers that prevent content-type sniffing and framing by other sites, restrict the
          referrer sent to other sites, and disable browser features the product does not use.
        </p>

        <h2>What depends on hosting</h2>
        <p>
          Encryption in transit requires the deployment to be served over HTTPS, and encryption at rest depends on the database and
          object storage used. Backups, disaster recovery and business continuity commitments have not yet been established for a
          production service. We will document the production configuration here before offering one.
        </p>

        <h2 id="reporting">Reporting a vulnerability</h2>
        <p>
          If you believe you have found a security issue, please tell us through the{" "}
          <Link href="/contact?topic=security">contact form</Link>, choosing “Security report”. Describe the issue and how to reach
          you, but do not include exploit details until we have replied with a secure channel.
        </p>
        <p>
          Please do not access data that is not yours, degrade the service, or use social engineering, and give us reasonable time
          to fix an issue before disclosing it. We do not currently offer a bug bounty, but we will acknowledge your report and keep
          you informed.
        </p>
      </PolicyBody>
    </>
  );
}
